version: "3.9"

services:
  tn-predictor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tn_election_predictor
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=7860
      - PYTHONPATH=/app
      - HF_ENABLE_REMOTE_SENTIMENT=false
    restart: unless-stopped